CREATE SEQUENCE SEQ1 START WITH 1;
CREATE TABLE TABLE1
(
    ID_COL    INT NOT NULL PRIMARY KEY,
    FIRST_COL VARCHAR2(20)
);
INSERT INTO TABLE1 (ID_COL, FIRST_COL)
VALUES (nextval('SEQ1'), 'VALUE1');
INSERT INTO TABLE1 (ID_COL, FIRST_COL)
VALUES (nextval('SEQ1'), 'VALUE2');
INSERT INTO TABLE1 (ID_COL, FIRST_COL)
VALUES (nextval('SEQ1'), 'VALUE3');
INSERT INTO TABLE1 (ID_COL, FIRST_COL)
VALUES (nextval('SEQ1'), 'VALUE4');
INSERT INTO TABLE1 (ID_COL, FIRST_COL)
VALUES (nextval('SEQ1'), 'VALUE5');