CREATE SEQUENCE SEQ1 START WITH 1;
CREATE TABLE TABLE1
(
    ID_COL     INT NOT NULL PRIMARY KEY,
    FIRST_COL  VARCHAR2(20),
    SECOND_COL VARCHAR2(20)
);
INSERT INTO TABLE1 (ID_COL, FIRST_COL, SECOND_COL)
VALUES (nextval('SEQ1'), 'VALUE_COL_1_ROW_1', 'VALUE_COL_2_ROW_1');
INSERT INTO TABLE1 (ID_COL, FIRST_COL, SECOND_COL)
VALUES (nextval('SEQ1'), 'VALUE_COL_1_ROW_2', 'VALUE_COL_2_ROW_2');
INSERT INTO TABLE1 (ID_COL, FIRST_COL, SECOND_COL)
VALUES (nextval('SEQ1'), 'VALUE_COL_1_ROW_3', 'VALUE_COL_2_ROW_3');
INSERT INTO TABLE1 (ID_COL, FIRST_COL, SECOND_COL)
VALUES (nextval('SEQ1'), 'VALUE_COL_1_ROW_4', 'VALUE_COL_2_ROW_4');
INSERT INTO TABLE1 (ID_COL, FIRST_COL, SECOND_COL)
VALUES (nextval('SEQ1'), 'VALUE_COL_1_ROW_5', 'VALUE_COL_2_ROW_5');